#Semana 2 - Exercício de apoio

#### 1. Carregue as bibliotecas NumPy e Pandas. 

In [6]:
import numpy as np
import pandas as pd

#### 2. Crie um NDArray com os seguintes valores [1, 2.5, 7, -78, -0.9, 130, 25].

In [2]:
lista = [1, 2.5, 7, -78, -0.9, 130, 25]

In [3]:
dados1 = np.array(lista)

In [4]:
dados1

array([  1. ,   2.5,   7. , -78. ,  -0.9, 130. ,  25. ])

#### 3. Crie um NDArray com os valores de 0 a 10. 

In [5]:
dadosseq = np.arange(11)

In [6]:
dadosseq

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 4. Crie um NDArray de dimensão 2x5 com valores 1.

In [7]:
dadosum = np.ones((2,5))

In [8]:
dadosum

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### 5. Crie um NDArray com valores de 1 a 100, com intervalos de 3 em 3.

In [9]:
dados3em3 = np.arange(1,101,3)

In [10]:
dados3em3

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

#### 6. Mostre as raízes quadradas dos valores do NDArray criado no exercício 5.

In [11]:
np.sqrt(dados3em3)

array([ 1.        ,  2.        ,  2.64575131,  3.16227766,  3.60555128,
        4.        ,  4.35889894,  4.69041576,  5.        ,  5.29150262,
        5.56776436,  5.83095189,  6.08276253,  6.32455532,  6.55743852,
        6.78232998,  7.        ,  7.21110255,  7.41619849,  7.61577311,
        7.81024968,  8.        ,  8.18535277,  8.36660027,  8.54400375,
        8.71779789,  8.88819442,  9.05538514,  9.21954446,  9.38083152,
        9.53939201,  9.69535971,  9.8488578 , 10.        ])

#### 7. Altere a décima posição do NDArray criado no exercício 5 com o dobro do seu valor.

In [12]:
dados3em3[9] = dados3em3[9]*2 

In [13]:
dados3em3

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  56,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

#### 8. Execute o comando para criar um DataFrame com os dados disponíveis no notebook. 

In [3]:
dados={'Empresa':['Microsoft', 'Google','Univesp','NVData Analytics','Power Bi Experience','USP'], 'Qtde Func':[1000, 1500,500, 100,100,499], 'Site':['https://www.microsoft.com/pt-br','https://www.google.com/','https://univesp.br/','https://www.nvdata.com.br/','https://powerbiexperience.com/pt/','https://www.usp.br/'],'Instagram':['@microsoft','@google','@univespoficial','@nv_data','@leokarpa','@usp.oficial'],'Criação':[1975,1998,2012,2019,2016,1934], 'País':['EUA','EUA','Brasil','Brasil','Brasil','Brasil']}

In [7]:
dfemp = pd.DataFrame(dados)

In [8]:
dfemp

Empresa  Qtde Func  ... Criação    País
0            Microsoft       1000  ...    1975     EUA
1               Google       1500  ...    1998     EUA
2              Univesp        500  ...    2012  Brasil
3     NVData Analytics        100  ...    2019  Brasil
4  Power Bi Experience        100  ...    2016  Brasil
5                  USP        499  ...    1934  Brasil

[6 rows x 6 columns]

#### 9. Execute um comando que seja possível identificar qual a média da quantidade de funcionários que as empresas listadas têm. Informe também a soma dos funcionários que as empresas têm. 

In [12]:
dfemp.describe(include='all')

Empresa    Qtde Func  ...      Criação    País
count                     6     6.000000  ...     6.000000       6
unique                    6          NaN  ...          NaN       2
top     Power Bi Experience          NaN  ...          NaN  Brasil
freq                      1          NaN  ...          NaN       4
mean                    NaN   616.500000  ...  1992.333333     NaN
std                     NaN   545.631286  ...    32.843061     NaN
min                     NaN   100.000000  ...  1934.000000     NaN
25%                     NaN   199.750000  ...  1980.750000     NaN
50%                     NaN   499.500000  ...  2005.000000     NaN
75%                     NaN   875.000000  ...  2015.000000     NaN
max                     NaN  1500.000000  ...  2019.000000     NaN

[11 rows x 6 columns]

In [26]:
somafunc = dfemp['Qtde Func'].sum()

In [27]:
somafunc

3699

#### 10. Mostre as primeiras 3 linhas do DataFrame. 

In [28]:
dfemp.head(3)

Empresa  Qtde Func  ... Criação    País
0  Microsoft       1000  ...    1975     EUA
1     Google       1500  ...    1998     EUA
2    Univesp        500  ...    2012  Brasil

[3 rows x 6 columns]

#### 11. Mostre as últimas 3 linhas do DataFrame.

In [29]:
dfemp.tail(3)

Empresa  Qtde Func  ... Criação    País
3     NVData Analytics        100  ...    2019  Brasil
4  Power Bi Experience        100  ...    2016  Brasil
5                  USP        499  ...    1934  Brasil

[3 rows x 6 columns]

#### 12. Liste apenas as linhas em que as empresas foram criadas nos últimos 10 anos. Informe a quantidade de registros. 

In [39]:
emp2010 = dfemp[dfemp["Criação"] > 2011]

In [38]:
emp2010

Empresa  Qtde Func  ... Criação    País
2              Univesp        500  ...    2012  Brasil
3     NVData Analytics        100  ...    2019  Brasil
4  Power Bi Experience        100  ...    2016  Brasil

[3 rows x 6 columns]

In [41]:
index = emp2010.index

In [43]:
qtdreg = len(index)

In [44]:
qtdreg

3

#### 13. Vamos imaginar que em todas as empresas exista 1 chefe para cada 23 funcionários. Crie uma coluna que mostre a quantidade de chefes que cada empresa teria, depois informe quantos chefes teríamos ao todo. (os valores não precisam ser números inteiros, é apenas uma estimativa). 

In [45]:
dfemp.insert(2, 'Qtde Chefes', dfemp['Qtde Func']/23, True)

In [46]:
dfemp

Empresa  Qtde Func  ...  Criação    País
0            Microsoft       1000  ...     1975     EUA
1               Google       1500  ...     1998     EUA
2              Univesp        500  ...     2012  Brasil
3     NVData Analytics        100  ...     2019  Brasil
4  Power Bi Experience        100  ...     2016  Brasil
5                  USP        499  ...     1934  Brasil

[6 rows x 7 columns]